spring:
  application:
    name: transactions-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactions

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      preferIpAddress: true

resilience4j:
  retry:
    instances:
      default:
        wait-duration: 5s